import SwiftUI
import Foundation

let allowedCategories: Set<String> = [
    "pizza",
    "sushi",
    "burger",
    "cafe",
    "dessert",
    "asian",
    "italian",
    "indian",
    "chinese",
    "middle eastern",
    "home food",
    "mexican",
    "thai",
    "japanese",
    "korean",
    "lebanese",
    "bbq",
    "steakhouse",
    "vegan",
    "vegetarian",
    "seafood",
    "falafel",
    "shawarma",
    "grill",
    "mediterranean",
    "bistro",
    "brunch",
    "bakery",
    "ice cream",
    "donuts",
    "ramen",
    "tapas",
    "noodles"
]

let categoryColors: [String: Color] = [
    "pizza": .orange,
    "sushi": .purple,
    "burger": .yellow,
    "cafe": .mint,
    "dessert": Color.pink.opacity(0.7),
    "asian": .teal,
    "italian": .green,
    "indian": .yellow,
    "chinese": .cyan,
    "middle eastern": .teal,
    "home food": .green,
    "mexican": .orange,
    "thai": .purple,
    "japanese": .blue,
    "korean": .indigo,
    "lebanese": .mint,
    "bbq": .orange,
    "steakhouse": .blue,
    "vegan": .green,
    "vegetarian": .mint,
    "seafood": .cyan,
    "falafel": .green,
    "shawarma": .yellow,
    "grill": .orange,
    "mediterranean": .teal,
    "bistro": .indigo,
    "brunch": Color.pink.opacity(0.7),
    "bakery": Color.pink.opacity(0.7),
    "ice cream": .teal,
    "donuts": .yellow,
    "ramen": .blue,
    "tapas": .purple,
    "noodles": .orange
]
